file <- read.table("household_power_consumption.txt",header = TRUE,sep = ";")
file[,"newT"] <- paste(as.character(file$Date) , as.character(file$Time))
file$Date <- as.Date(as.character(file$Date),format = "%d/%m/%Y")
data <- subset(file,Date>="2007-02-01" & Date<="2007-02-02")
data$Global_active_power<- as.numeric(as.character(data$Global_active_power))
data$newT <- strptime(data$newT, format = "%d/%m/%Y %H:%M:%S")
png(filename = "plot2.png", width = 480, height = 480, units = "px")
plot(data$newT,data$Global_active_power, type="l", xlab="",ylab="Global Active Power (kilowatts)")
dev.off()