file <- read.table("household_power_consumption.txt",header = TRUE,sep = ";")
file[,"newT"] <- paste(as.character(file$Date) , as.character(file$Time))
file$Date <- as.Date(as.character(file$Date),format = "%d/%m/%Y")
file$Time <- strptime(file$Time, format = "%H:%M:%S")
data <- subset(file,Date>="2007-02-01" & Date<="2007-02-02")
data$Global_active_power<- as.numeric(as.character(data$Global_active_power))
data$Global_reactive_power<- as.numeric(as.character(data$Global_reactive_power))
data[,7] <- as.numeric(as.character(data[,7]))
data[,8] <- as.numeric(as.character(data[,8]))
data[,5] <- as.numeric(as.character(data[,5]))
data$newT <- strptime(data$newT, format = "%d/%m/%Y %H:%M:%S")
png(filename = "plot4.png", width = 480, height = 480, units = "px")
par(mfrow=c(2,2))
plot(data$newT,data$Global_active_power, type="l", xlab="",ylab="Global Active Power (kilowatts)")
plot(data$newT,data$Voltage, type="l",xlab = "datetime",ylab = "Voltage")
plot(data$newT,data[,7], type="l", col="black", xlab="", ylab="Energy sub metering")
lines(data$newT,data[,8], col="red")
lines(data$newT,data[,9], col="blue")
legend(x="topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lwd=0.8, cex=0.8)
plot(data$newT,data$Global_reactive_power,type="l",xlab = "datetime", ylab = "Global_reactive_power",cex.axis=0.8)
dev.off()
