file <- read.table("household_power_consumption.txt",header = TRUE,sep = ";")
file[,"newT"] <- paste(as.character(file$Date) , as.character(file$Time))
file$Date <- as.Date(as.character(file$Date),format = "%d/%m/%Y")
data <- subset(file,Date>="2007-02-01" & Date<="2007-02-02")
data[,7] <- as.numeric(as.character(data[,7]))
data[,8] <- as.numeric(as.character(data[,8]))
data$newT <- strptime(data$newT, format = "%d/%m/%Y %H:%M:%S")
png(filename = "plot3.png", width = 480, height = 480, units = "px")
plot(data$newT,data[,7], type="l", col="black", xlab="", ylab="Energy sub metering")
lines(data$newT,data[,8], col="red")
lines(data$newT,data[,9], col="blue")
legend(x="topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lwd=1)
dev.off()

