  file <- read.table("household_power_consumption.txt",header = TRUE,sep = ";")
  file$Date <- as.Date(as.character(file$Date),format = "%d/%m/%Y")
  file$Time <- strptime(file$Time, format = "%H:%M:%S")
  data <- subset(file,Date>="2007-02-01" & Date<="2007-02-02")
  data$Global_active_power<- as.numeric(as.character(data$Global_active_power))
  par(mfrow=c(1,1))
  par(mar=c(4,4,2,2))
  png(filename = "plot1.png", width = 480, height = 480, units = "px")
  hist(data$Global_active_power,col="red", main="Global Active Power", xlab = "Global Active Power (Kilowatts)")
  dev.off()